/* =========================================================
   LIFEFUND PR実績アーカイブ／メディアキット／紹介文集 — 予備データ
   ---------------------------------------------------------
   受付係（Apps Script）からデータを取れないときだけ使われる控え。
   2026-09-27 時点のスプレッドシートの内容を書き出したもの。
   ふだんの更新はスプレッドシートで行い、このファイルは直さなくてよい。
   ========================================================= */

const FALLBACK_DATA = {
  lastUpdated: "2026-09-27",

  press: [
    {"date":"2026/08/14","title":"逆風の住宅市場で“縮小”ではなく“拡張”を――『BLUEPRINT 2036』の半年の進捗と次の一手を報告、LIFEFUNDが下期経営方針発表会を実施","url":"https://prtimes.jp/main/html/rd/p/000000096.000160136.html"},
    {"date":"2026/08/13","title":"【調査リリース】建築業界経営者向けAIコミュニティ参加とAI活用の関係を調査――建築AI経営研究会の会員は組織活用82.8%、非会員は52.0%","url":"https://prtimes.jp/main/html/rd/p/000000095.000160136.html"},
    {"date":"2026/08/13","title":"【調査リリース】AIを\"組織で活用\"する企業が半年で43.4%から68.5%に拡大――建築業界の経営者調査、次の論点は\"人材育成\"と\"効果の定量化\"へ","url":"https://prtimes.jp/main/html/rd/p/000000094.000160136.html"},
    {"date":"2026/08/14","title":"【開催報告】社員主役の「AI事例共有会」を本格導入、現場発の自動化を“全社の共有知”へ——”AIを活用できる社内人材がいない、育てていない”の声に応えるLIFEFUNDの実践","url":"https://prtimes.jp/main/html/rd/p/000000093.000160136.html"},
    {"date":"2026/08/18","title":"【2026年9月28日(月)開催】社長の判断軸をAIで全社へ——第６回 建築AI経営研究会は“社長AI”をテーマに開催","url":"https://prtimes.jp/main/html/rd/p/000000092.000160136.html"},
    {"date":"2026/08/18","title":"建築業界の「AIを配ったのに使われない」にどう対策？——建築業経営者ら約130名が学んだ“AI組織浸透”の実践、第5回 建築AI経営研究会をLIFEFUNDが開催","url":"https://prtimes.jp/main/html/rd/p/000000090.000160136.html"},
    {"date":"2026/08/10","title":"【9月8日(火)16:00開催】「AIがあれば、既存システムはいらない？」――LIFEFUND×ダイテック、建築業の\"AI×DX二刀流経営\"をオンラインで対談解説","url":"https://prtimes.jp/main/html/rd/p/000000089.000160136.html"},
    {"date":"2026/08/10","title":"【登壇報告】建築業界のAI検索対策とAIエージェントの全社活用を公開――LIFEFUND代表白都卓磨氏、JGBA主催「若手経営者トークセッション」にて","url":"https://prtimes.jp/main/html/rd/p/000000088.000160136.html"},
    {"date":"2026/08/10","title":"LIFEFUND、建築業界向け「Codex活用」「AI入門」セミナーを開催。工務店業務のAI実装例を共有","url":"https://prtimes.jp/main/html/rd/p/000000087.000160136.html"},
    {"date":"2026/08/13","title":"建築業界「AI活用100本ノック」2026年第2四半期版を無料公開――建築会社の実務で試した最新の100事例を、課題・進め方・成果・“人が確認すべき点”まで","url":"https://prtimes.jp/main/html/rd/p/000000086.000160136.html"},
    {"date":"2026/08/11","title":"建築業のAI実務デモ3本・経営Q&A7本を会員向けに追加公開――建築AI経営研究会","url":"https://prtimes.jp/main/html/rd/p/000000085.000160136.html"},
    {"date":"2026/08/19","title":"地震・省エネ性能を「体感」して理解する必要性","url":"https://prtimes.jp/main/html/rd/p/000000083.000160136.html"},
    {"date":"2026/07/31","title":"【満足度100％】「建築・リフォーム業の『実務×AI』」の最前線をLIFEFUNDとSpeeeが公開","url":"https://prtimes.jp/main/html/rd/p/000000081.000160136.html"},
    {"date":"2026/06/19","title":"【2026年8月3日(月)】工務店のAI活用を「一部の人だけ」から「全社で使いたくなる」へ――第5回建築AI経営研究会で「社内浸透」の実践手法を公開","url":"https://prtimes.jp/main/html/rd/p/000000078.000160136.html"},
    {"date":"2026/06/18","title":"工務店経営にAIエージェントを組み込む実践事例を公開。第4回建築AI経営研究会に150名が参加","url":"https://prtimes.jp/main/html/rd/p/000000068.000160136.html"},
    {"date":"2026/06/17","title":"【調査リリース】建築AI経営研究会の会員・非会員にみる行動・仕組みの差——社員AI教育投資、AI活用の組織化、Claude会社導入率等で顕著。","url":"https://prtimes.jp/main/html/rd/p/000000079.000160136.html"},
    {"date":"2026/06/17","title":"採用難の建築業界で、AI・DXと組織づくりをどう進める？　LIFEFUNDと楓工務店が共催セミナーを開催","url":"https://prtimes.jp/main/html/rd/p/000000077.000160136.html"},
    {"date":"2026/06/16","title":"【調査リリース】建築業界のAI組織活用、43.4%から61.3%へ。経営者調査で見えた次の壁は「社内浸透」","url":"https://prtimes.jp/main/html/rd/p/000000070.000160136.html"},
    {"date":"2026/06/16","title":"【7月30日(木)開催】リフォーム産業フェア2026で若手経営者5名が公開討論、LIFEFUND代表 白都卓磨が登壇","url":"https://prtimes.jp/main/html/rd/p/000000075.000160136.html"},
    {"date":"2026/06/15","title":"【6月25日(木)開催】建築業界×Claude Code完全攻略セミナーをリバイバル上映、初回25名参加・満足度100%を受け再配信","url":"https://prtimes.jp/main/html/rd/p/000000076.000160136.html"},
    {"date":"2026/06/15","title":"【2026年7月6日(月)開催】追客・カラー提案・積算をAIで効率化。建築・リフォーム業向け「実務×AI」セミナーをLIFEFUND×Speeeが共催","url":"https://prtimes.jp/main/html/rd/p/000000074.000160136.html"},
    {"date":"2026/06/12","title":"ナフサ危機下の顧客対応をAIで標準化。月刊アーキテクトビルダー6月号にLIFEFUND事例掲載","url":"https://prtimes.jp/main/html/rd/p/000000072.000160136.html"},
    {"date":"2026/06/11","title":"建築AIの現場実演動画9本を公開。契約・積算・設計など工務店業務をノーカットで解説――建築AI経営研究会","url":"https://prtimes.jp/main/html/rd/p/000000069.000160136.html"},
    {"date":"2026/06/04","title":"全社AI活用は1割未満の建築業界、正社員55名中28名参加の社内AI推進モデルをLIFEFUNDが公開","url":"https://prtimes.jp/main/html/rd/p/000000064.000160136.html"},
    {"date":"2026/06/03","title":"「AIを使わない選択は、緩やかな倒産である」売上を2億から27億に伸ばした工務店経営者が業界へ提言――物件王セミナーにLIFEFUND代表白都卓磨氏が登壇","url":"https://prtimes.jp/main/html/rd/p/000000066.000160136.html"},
    {"date":"2026/06/02","title":"3カ月で422件の事例創出の工務店がAI活用アイデアを公開、新建ハウジング主催セミナーにLIFEFUND代表白都卓磨が登壇。","url":"https://prtimes.jp/main/html/rd/p/000000065.000160136.html"},
    {"date":"2026/06/01","title":"【2026年6月9日(火)開催】これからの10年、生き残る工務店の条件は「AI・DX」と「人が育つ仕組み」――LIFEFUND代表白都卓磨氏と楓工務店代表田尻忠義氏が対談形式で語る","url":"https://prtimes.jp/main/html/rd/p/000000063.000160136.html"},
    {"date":"2026/05/01","title":"ナフサ危機の対応にAI活用。建築AI経営研究会を運営する浜松の工務店が事例紹介","url":"https://prtimes.jp/main/html/rd/p/000000062.000160136.html"},
    {"date":"2026/05/01","title":"【2026年6月2日(火)】第４回建築AI経営研究会を開催。東京会場とオンライン会場のハイブリッド方式","url":"https://prtimes.jp/main/html/rd/p/000000061.000160136.html"},
    {"date":"2026/05/01","title":"建築業界「AI活用100本ノック」を公開します――現場で試してきた100のAI活用事例","url":"https://prtimes.jp/main/html/rd/p/000000060.000160136.html"},
    {"date":"2026/05/01","title":"【続報】浜松の工務店からの注意喚起。ナフサ危機が住宅建材を直撃——性能を損なわない代替調達と事前合意書面による対応を開始","url":"https://prtimes.jp/main/html/rd/p/000000058.000160136.html"},
    {"date":"2026/04/30","title":"【2026年5月25日(月)開催】売上2億→27億の現役工務店社長が語る、AI経営の実装法──LIFEFUND白都卓磨が物件王主催セミナーに登壇","url":"https://prtimes.jp/main/html/rd/p/000000057.000160136.html"},
    {"date":"2026/04/30","title":"【調査リリース】「他社はどこまでAI使っている？」住宅・建築業界経営者53名の本音調査 ―― 個人利用は9割、組織活用は1割","url":"https://prtimes.jp/main/html/rd/p/000000053.000160136.html"},
    {"date":"2026/04/30","title":"建築業界の危機はナフサだけじゃない——人を増やさず売上を伸ばす「営業×AI」、人手不足と市場縮小に直面する105社の経営者が学んだ最新事例","url":"https://prtimes.jp/main/html/rd/p/000000052.000160136.html"},
    {"date":"2026/04/29","title":"【5月15日(金)13時開催】\"工務店業務のAI活用\"の最先端を6名のトップランナーが共有。LIFEFUND代表 白都卓磨が新建ハウジング主催オンラインセミナーに登壇","url":"https://prtimes.jp/main/html/rd/p/000000054.000160136.html"},
    {"date":"2026/04/09","title":"相続の悩み、工務店に持ち込まれる時代に——相続セミナーが2カ月連続で満席、約6割がその場で個別面談を希望","url":"https://prtimes.jp/main/html/rd/p/000000050.000160136.html"},
    {"date":"2026/03/30","title":"浜松の工務店からの注意喚起。ナフサ危機が住宅建材を直撃——断熱材の供給不安と工期遅延、住宅を計画中の方に今知ってほしいこと","url":"https://prtimes.jp/main/html/rd/p/000000051.000160136.html"},
    {"date":"2026/03/27","title":"赤字1,000万円でも止めなかった住宅会社のマルシェ、7年で来場2.9万人に","url":"https://prtimes.jp/main/html/rd/p/000000046.000160136.html"},
    {"date":"2026/03/26","title":"建築業界のAI活用事例33本を動画で公開、業界特化型プラットフォームを提供開始","url":"https://prtimes.jp/main/html/rd/p/000000043.000160136.html"},
    {"date":"2026/03/26","title":"堀江貴文氏と語る建築AI「ベテランほどAIと相性がいい」","url":"https://prtimes.jp/main/html/rd/p/000000047.000160136.html"},
    {"date":"2026/03/25","title":"「AIを使ったら給料が上がる」にしたら、3ヶ月で社員から177件の活用事例が溢れた話","url":"https://prtimes.jp/main/html/rd/p/000000044.000160136.html"},
    {"date":"2026/03/23","title":"住宅ローン上昇・人手不足・倒産増。それでも浜松の工務店社長は「拡張」を選んだ","url":"https://prtimes.jp/main/html/rd/p/000000042.000160136.html"},
    {"date":"2026/03/23","title":"堀江貴文氏が仕掛ける「AI版令和の虎」にLIFEFUND代表白都卓磨が出演","url":"https://prtimes.jp/main/html/rd/p/000000041.000160136.html"},
    {"date":"2026/02/07","title":"顧客を職人に変える工務店。オーナー感謝祭で学ぶ「家の守り方」","url":"https://prtimes.jp/main/html/rd/p/000000025.000160136.html"},
    {"date":"2026/02/06","title":"【JGBA主催】なぜ10年で「年間100棟」ビルダーになれたのか？売上13倍を実現し、AIスクールを運営するLIFEFUNDがAI活用術と成長戦略を大公開","url":"https://prtimes.jp/main/html/rd/p/000000021.000160136.html"},
    {"date":"2026/02/06","title":"「ホリエモンAI学校 建築校」公式サイトを全面刷新。検索性と実用性を大幅強化","url":"https://prtimes.jp/main/html/rd/p/000000019.000160136.html"},
    {"date":"2026/01/28","title":"2/2開催 現役工務店が語る一人売上7000万 建築AI経営研究会","url":"https://prtimes.jp/main/html/rd/p/000000018.000160136.html"},
    {"date":"2026/01/23","title":"AIで建築パースを1分作成、750社参加の生成AI講座を刷新","url":"https://prtimes.jp/main/html/rd/p/000000017.000160136.html"},
    {"date":"2026/01/13","title":"10年で売上13倍の建設会社が、年間休日120日に踏み切った理由","url":"https://prtimes.jp/main/html/rd/p/000000016.000160136.html"},
    {"date":"2026/01/08","title":"住宅着工件数が減り続ける中、なぜこの会社は10年で売上12倍になったのか——浜松の工務店が見つけた「縮小市場の勝ち筋」","url":"https://prtimes.jp/main/html/rd/p/000000014.000160136.html"},
    {"date":"2025/12/04","title":"AIで建築業界に革新を仕掛けるのは地方の工務店だった——静岡県浜松市にて「建築AI経営研究会」が初開催、全国から経営者が集結し、満足度は95%超","url":"https://prtimes.jp/main/html/rd/p/000000012.000160136.html"},
    {"date":"2025/12/02","title":"AI駆使の工務店に全国から視線が集中！ Japan Home Show 2025「工務店経営会議2025」のLIFEFUND代表・白都卓磨の登壇セッションが大反響、690人が参加","url":"https://prtimes.jp/main/html/rd/p/000000013.000160136.html"},
    {"date":"2025/11/18","title":"建築業界を\"高生産産業\"へ——ARRCH・PG HOUSEを運営する株式会社LIFEFUND、建築AI経営研究会を発足","url":"https://prtimes.jp/main/html/rd/p/000000011.000160136.html"},
    {"date":"2025/11/14","title":"【11月21日セミナー開催】「工務店経営会議2025」に株式会社LIFEFUND代表取締役 白都卓磨が登壇！【Japan Home Show & Building Show 2025】","url":"https://prtimes.jp/main/html/rd/p/000000010.000160136.html"},
    {"date":"2025/08/28","title":"8/25開催の「建築×AI」ウェビナーが大盛況！150名以上が参加、満足度90%以上を記録","url":"https://prtimes.jp/main/html/rd/p/000000007.000160136.html"},
    {"date":"2025/08/17","title":"【残り10社】先着100社限定・無料オンラインセミナー「建築業界のための\"即実践\"AI仕事術セミナー」","url":"https://prtimes.jp/main/html/rd/p/000000006.000160136.html"},
    {"date":"2025/07/25","title":"即実践できるAI活用術を公開！ホリエモンAI学校建築校が無料オンラインセミナー開催","url":"https://prtimes.jp/main/html/rd/p/000000005.000160136.html"},
    {"date":"2025/07/25","title":"ホリエモンAI学校「建築校」開校——工務店が運営する建築業に特化したAIスクールが始動！","url":"https://prtimes.jp/main/html/rd/p/000000004.000160136.html"},
    {"date":"2025/06/29","title":"「PG HOUSE 浜松」、全国14社42名の工務店関係者が視察に来場！青汁王子・三崎優太氏のYouTubeチャンネルでも紹介されました！","url":"https://prtimes.jp/main/html/rd/p/000000003.000160136.html"},
    {"date":"2025/04/28","title":"【5/18(日)】過去最多70店舗が出店！浜松の人気グルメ・雑貨が集結。「湖のマルシェ」、浜松城公園で開催","url":"https://prtimes.jp/main/html/rd/p/000000002.000160136.html"},
    {"date":"2025/04/28","title":"【5/9(金)】0度の世界で断熱性能の違いを体験！PGパークお披露目会にメディア関係者様をご招待！","url":"https://prtimes.jp/main/html/rd/p/000000001.000160136.html"},
  ],

  media: [
    {"date":"2026/07/30","title":"【メディア掲載】弊社のAIの取り組み「建築AI経営研究会」が建設・住宅業界の専門紙に紹介されました","brand":"ARRCH/PGHOUSE","url1":"https://www.arrch.net/article/p12165/","label1":"ARRCH","url2":"https://hamamatsu.pg-house.jp/news/pg-house-media-202607/","label2":"PGHOUSE"},
    {"date":"2026/07/22","title":"【メディア掲載】雑誌「リンネル」2026年9月号にARRCHの家が掲載されました！","brand":"ARRCH","url1":"https://www.arrch.net/article/p12114/","label1":"ARRCH","url2":"","label2":""},
    {"date":"2026/06/11","title":"【メディア掲載】新建ハウジング「アーキテクトビルダー」が注目！PG HOUSEが貫く「事実を伝える誠実な家づくり」","brand":"ARRCH/PGHOUSE","url1":"https://hamamatsu.pg-house.jp/news/honest-house-building/","label1":"PGHOUSE","url2":"https://www.arrch.net/article/architect-sincerity-house/","label2":"ARRCH"},
    {"date":"2026/05/14","title":"【メディア掲載】施主様のお家がLIXILカタログに掲載決定","brand":"PGHOUSE","url1":"https://hamamatsu.pg-house.jp/news/featured-in-lixil/","label1":"PGHOUSE","url2":"","label2":""},
    {"date":"2026/04/28","title":"【メディア掲載】K-MIX ビルダーズラジオに弊社代表が出演しました！","brand":"ARRCH/PGHOUSE","url1":"https://www.arrch.net/article/p10815/","label1":"ARRCH","url2":"https://hamamatsu.pg-house.jp/news/%e3%80%90%e3%83%a1%e3%83%87%e3%82%a3%e3%82%a2%e6%8e%b2%e8%bc%89%e3%80%91%e5%bc%8a%e7%a4%be%e4%bb%a3%e8%a1%a8%e3%81%8c%e3%83%a9%e3%82%b8%e3%82%aa%e3%81%ab%e5%87%ba%e6%bc%94%e3%81%97%e3%81%be%e3%81%97/","label2":"PGHOUSE"},
    {"date":"2026/04/26","title":"【メディア掲載】住宅業界を揺るがす「ナフサ不足」の深刻な影響について — ABEMA・NHK各局で紹介されました","brand":"ARRCH/PGHOUSE","url1":"https://www.arrch.net/article/p10787/","label1":"ARRCH","url2":"https://hamamatsu.pg-house.jp/news/%e3%80%90%e3%83%a1%e3%83%87%e3%82%a3%e3%82%a2%e6%8e%b2%e8%bc%89%e3%80%91abema%e3%83%bbnhk%e5%90%84%e5%b1%80%e3%81%ab%e3%80%8c%e4%bd%8f%e5%ae%85%e6%a5%ad%e7%95%8c%e3%82%92%e6%8f%ba%e3%82%8b%e3%81%8c/","label2":"PGHOUSE"},
    {"date":"2026/04/26","title":"【メディア掲載】バチャナビに「株式会社LIFEFUNDのオフィス取材記事」が紹介されました","brand":"ARRCH/PGHOUSE","url1":"https://www.arrch.net/article/p10644/","label1":"ARRCH","url2":"https://hamamatsu.pg-house.jp/news/%e3%80%90%e3%83%a1%e3%83%87%e3%82%a3%e3%82%a2%e6%8e%b2%e8%bc%89%e3%80%91%e3%83%90%e3%83%81%e3%83%a3%e3%83%8a%e3%83%93%e3%81%ab%e3%80%8cpg-house%e3%81%ae%e3%82%aa%e3%83%95%e3%82%a3%e3%82%b9%e3%80%8d/","label2":"PGHOUSE"},
    {"date":"2026/04/26","title":"【メディア掲載】『住宅産業新聞』『TACT』に紹介いただきました","brand":"ARRCH/PGHOUSE","url1":"https://www.arrch.net/article/p10638/","label1":"ARRCH","url2":"https://hamamatsu.pg-house.jp/news/%e3%80%90%e3%83%a1%e3%83%87%e3%82%a3%e3%82%a2%e6%8e%b2%e8%bc%89%e3%80%91%e3%80%8e%e4%bd%8f%e5%ae%85%e7%94%a3%e6%a5%ad%e6%96%b0%e8%81%9e%e3%80%8f%e3%80%8etact%e3%80%8f%e3%81%ab%e7%b4%b9%e4%bb%8b/","label2":"PGHOUSE"},
    {"date":"2026/04/15","title":"【メディア掲載】「倒産しない住宅会社」の選び方とは？集英社発行週刊誌にて弊社代表・白都が解説","brand":"ARRCH","url1":"https://www.arrch.net/article/p10378/","label1":"ARRCH","url2":"","label2":""},
    {"date":"2026/04/07","title":"【カタログ掲載】名古屋モザイク最新カタログにARRCHの施工事例が選ばれました","brand":"ARRCH","url1":"https://www.arrch.net/article/p10269/","label1":"ARRCH","url2":"","label2":""},
    {"date":"2026/03/16","title":"【メディア掲載】Webメディア『施工の神様』に「工務店経営を変えるAI活用の5ステップ」が紹介されました","brand":"ARRCH/PGHOUSE","url1":"https://www.arrch.net/article/p9817/","label1":"ARRCH","url2":"https://hamamatsu.pg-house.jp/news/future-housing-ai/","label2":"PGHOUSE"},
    {"date":"2026/03/09","title":"【メディア掲載】『リフォーム産業新聞』にて、弊社の「建築AI経営研究会」の取り組みが紹介されました","brand":"ARRCH/PGHOUSE","url1":"https://www.arrch.net/article/p9703/","label1":"ARRCH","url2":"https://hamamatsu.pg-house.jp/news/ai-house-building260309/","label2":"PGHOUSE"},
    {"date":"2026/02/19","title":"【メディア出演】ホリエモンチャンネルに弊社代表が出演しました","brand":"ARRCH/PGHOUSE","url1":"https://www.arrch.net/article/p9187/","label1":"ARRCH","url2":"https://hamamatsu.pg-house.jp/news/ai-house-building-cospa/","label2":"PGHOUSE"},
    {"date":"2026/01/27","title":"【メディア掲載】建設業界大手サイト「施工の神様」に当社のAI活用と家づくりの未来が特集されました","brand":"ARRCH/PGHOUSE","url1":"https://www.arrch.net/article/p8677/","label1":"ARRCH","url2":"https://hamamatsu.pg-house.jp/news/20260127/","label2":"PGHOUSE"},
    {"date":"2026/01/16","title":"【掲載情報】LIFEFUNDのAI人材育成の取り組みが業界紙に掲載されました｜PG HOUSEが大切にする家づくりの考え方","brand":"ARRCH/PGHOUSE","url1":"https://www.arrch.net/article/p8585/","label1":"ARRCH","url2":"https://hamamatsu.pg-house.jp/news/260115/","label2":"PGHOUSE"},
    {"date":"2025/11/28","title":"【掲載情報】PGパーク浜松が住宅産業新聞で取り上げられました","brand":"PGHOUSE","url1":"https://hamamatsu.pg-house.jp/news/","label1":"PGHOUSE","url2":"","label2":""},
    {"date":"2025/11/28","title":"PG HOUSEの家づくりが全国に発信されました｜「工務店経営会議2025」に代表・白都が登壇","brand":"PGHOUSE","url1":"https://hamamatsu.pg-house.jp/news/","label1":"PGHOUSE","url2":"","label2":""},
    {"date":"2025/10/06","title":"弊社代表が「社長名鑑」に掲載されました","brand":"ARRCH/PGHOUSE","url1":"https://www.arrch.net/article/p6950/","label1":"ARRCH","url2":"https://hamamatsu.pg-house.jp/news/","label2":"PGHOUSE"},
    {"date":"2025/10/02","title":"【掲載情報】@DIMEに「PG HOUSE」が紹介されました｜半額以下で建てられる高性能注文住宅の秘密","brand":"PGHOUSE","url1":"https://hamamatsu.pg-house.jp/news/2510/","label1":"PGHOUSE","url2":"","label2":""},
    {"date":"2025/06/26","title":"【特別来訪】青汁王子・三崎優太氏がPGパークを訪問｜「この性能でこの価格!?」驚きの対談も公開中","brand":"PGHOUSE","url1":"https://hamamatsu.pg-house.jp/news/2506/","label1":"PGHOUSE","url2":"","label2":""},
  ],

  talks: [
    {"date":"2026/09/28","event":"第6回 建築AI経営研究会","venue":"東京・八重洲","session":"第6回 建築AI経営研究会の基調講演に代表取締役の白都卓磨が登壇","theme":"","attendees":"150社","satisfaction":"","event_url":"https://prtimes.jp/main/html/rd/p/000000092.000160136.html","video_url":"","report_url":""},
    {"date":"2026/09/08","event":"ダイテック共催「建築業のAI×DX二刀流経営」セミナー","venue":"オンライン","session":"AIをテーマとした対談形式セミナーにダイテックの江谷晃氏と代表取締役の白都卓磨が登壇","theme":"建築業のAI×DX二刀流経営","attendees":"","satisfaction":"","event_url":"https://prtimes.jp/main/html/rd/p/000000089.000160136.html","video_url":"","report_url":""},
    {"date":"2026/08/03","event":"第5回 建築AI経営研究会","venue":"東京・品川","session":"第5回 建築AI経営研究会の基調講演に代表取締役白都卓磨が登壇","theme":"","attendees":"150社","satisfaction":"","event_url":"https://prtimes.jp/main/html/rd/p/000000078.000160136.html","video_url":"","report_url":""},
    {"date":"2026/07/30","event":"JGBA主催「住宅業界停滞か成長か？若手経営者が挑む次の一手」シンポジウム","venue":"東京ビッグサイト","session":"JGBA主催シンポジウムに代表取締役の白都卓磨が若手経営者５名と登壇","theme":"「住宅業界停滞か成長か？若手経営者が挑む次の一手」","attendees":"","satisfaction":"","event_url":"https://prtimes.jp/main/html/rd/p/000000075.000160136.html","video_url":"","report_url":""},
    {"date":"2026/07/09","event":"Speee共催「建築・リフォーム業の実務×AI最前線」セミナー","venue":"オンライン","session":"AIをテーマとした対談形式セミナーにSpeeeの箕輪憲太氏と代表取締役の白都卓磨が登壇","theme":"「建築・リフォーム業の実務×AI最前線」","attendees":"","satisfaction":"","event_url":"https://prtimes.jp/main/html/rd/p/000000074.000160136.html","video_url":"","report_url":""},
    {"date":"2026/06/09","event":"楓工務店共催「これからの10年、生き残る工務店の条件は「AI・DX」と「人が育つ仕組み」」セミナー","venue":"オンライン","session":"DXとAIをテーマとした対談形式セミナーに楓工務店の田尻忠義氏と代表取締役の白都卓磨が登壇","theme":"これからの10年、生き残る工務店の条件は「AI・DX」と「人が育つ仕組み」","attendees":"","satisfaction":"","event_url":"https://prtimes.jp/main/html/rd/p/000000063.000160136.html","video_url":"","report_url":""},
    {"date":"2026/06/02","event":"第4回 建築AI経営研究会","venue":"東京・八重洲","session":"第4回 建築AI経営研究会の基調講演に代表取締役の白都卓磨が登壇","theme":"","attendees":"150社","satisfaction":"","event_url":"https://prtimes.jp/main/html/rd/p/000000061.000160136.html","video_url":"","report_url":""},
    {"date":"2026/05/25","event":"物件王主催「工務店経営×AI！売上を2億から27億にした現役社長が語る活用事例と未来戦略」セミナー","venue":"オンライン","session":"物件王主催セミナーに代表取締役の白都卓磨が登壇","theme":"LIFEFUNDが自社で実装してきた「AIの社内浸透」と「建築業特化型AI教育の仕組み化」を解説","attendees":"","satisfaction":"","event_url":"https://prtimes.jp/main/html/rd/p/000000066.000160136.html","video_url":"","report_url":""},
    {"date":"2026/05/15","event":"新建ハウジング主催「工務店AI・検証スペシャル 業界トップランナーが語る。工務店AI活用の最前線」セミナー","venue":"YOUTUBE","session":"新建ハウジング主催youtube番組に代表取締役白都卓磨が建築業界の第一人者5名と出演","theme":"「工務店AI・検証スペシャル 業界トップランナーが語る。工務店AI活用の最前線」","attendees":"","satisfaction":"","event_url":"https://prtimes.jp/main/html/rd/p/000000065.000160136.html","video_url":"","report_url":""},
    {"date":"2026/03/30","event":"第3回 建築AI経営研究会","venue":"東京・京橋","session":"第3回 建築AI経営研究会の基調講演に代表取締役の白都卓磨が登壇","theme":"","attendees":"105社","satisfaction":"","event_url":"https://prtimes.jp/main/html/rd/p/000000052.000160136.html","video_url":"","report_url":""},
    {"date":"2026/03/16","event":"「AI版令和の虎」","venue":"YOUTUBE","session":"「AI版令和の虎」第1回に代表取締役の白都卓磨が虎として出演","theme":"｢AIの力で命を守る！｣美容医療の麻酔関連事故をAIの力でゼロにしたい【内田 達士】[1人目]AI版令和の虎","attendees":"","satisfaction":"","event_url":"https://www.youtube.com/watch?v=M2moDw2XEa4","video_url":"","report_url":""},
    {"date":"2026/03/10","event":"滋賀県「木の家倶楽部」主催 講演会","venue":"京都","session":"木の家倶楽部主催の講演会に代表取締役の白都卓磨が登壇","theme":"売上13倍を実現したAI活用術と成長戦略","attendees":"","satisfaction":"","event_url":"https://murachi.com/business/business16/","video_url":"","report_url":""},
    {"date":"2026/02/27","event":"安心計画主催「AIで売れる住宅提案の実践戦略」セミナー","venue":"オンライン","session":"安心計画主催セミナーに代表取締役の白都卓磨が登壇","theme":"【WEB】「年間100棟のトップビルダーが語る!AIで売れる住宅提案の実践戦略 ～現場で\"使えるAI\"をどう選び、どう組み合わせるか～」","attendees":"","satisfaction":"","event_url":"https://www.anshin.co.jp/event/770","video_url":"","report_url":""},
    {"date":"2026/02/15","event":"堀江貴文氏「ホリエモンチャンネル」","venue":"YOUTUBE","session":"「建築業界×AI」をテーマに堀江貴文氏と代表取締役の白都卓磨が対談","theme":"現役の建築会社が運営？工務店・建設会社専門のAI導入支援「ホリエモンAI学校建築校」とは？","attendees":"","satisfaction":"","event_url":"https://www.youtube.com/watch?v=ErxNpkWLzdM","video_url":"","report_url":""},
    {"date":"2026/02/10","event":"JGBA主催「縮小市場でも伸びる工務店　成長戦略 × AIがつくる次の10年」セミナー","venue":"オンライン","session":"JGBA主催セミナーに代表取締役の白都卓磨が登壇","theme":"「縮小市場でも伸びる工務店　成長戦略 × AIがつくる次の10年」","attendees":"","satisfaction":"","event_url":"","video_url":"","report_url":""},
    {"date":"2026/02/02","event":"第2回 建築AI経営研究会","venue":"東京・品川","session":"第2回 建築AI経営研究会の基調講演に代表取締役白都卓磨が登壇","theme":"","attendees":"","satisfaction":"","event_url":"https://prtimes.jp/main/html/rd/p/000000018.000160136.html","video_url":"","report_url":""},
    {"date":"2025/11/21","event":"Japan Home Show & Building Show 2025","venue":"東京ビッグサイト","session":"新建ハウジング主催「工務店経営会議2025 登壇セッション」に代表取締役白都卓磨が登壇","theme":"AI駆使の工務店に全国から視線が集中。10年で売上12倍を達成した戦略を公開","attendees":"","satisfaction":"","event_url":"https://prtimes.jp/main/html/rd/p/000000013.000160136.html","video_url":"","report_url":""},
    {"date":"2025/11/26","event":"第1回 建築AI経営研究会","venue":"静岡・浜松","session":"第1回 建築AI経営研究会の基調講演に代表取締役白都卓磨が登壇","theme":"","attendees":"","satisfaction":"","event_url":"https://prtimes.jp/main/html/rd/p/000000012.000160136.html","video_url":"","report_url":""},
    {"date":"2025/10/28","event":"casa project LEGACYがLIFEFUNDのARRCHブランドを視察","venue":"静岡・浜松","session":"casa project LEGACYがLIFEFUNDのARRCHブランドを視察。代表取締役の白都卓磨が講演。","theme":"","attendees":"","satisfaction":"","event_url":"","video_url":"","report_url":""},
    {"date":"2025/07/25","event":"CROSS FM「堀江貴文ナビゲート『ホリスペ！』　」","venue":"ラジオ・YOUTUBE","session":"CROSS FM「堀江貴文ナビゲート『ホリスペ！』　」に代表取締役の白都卓磨が出演","theme":"『AI × 建築』をテーマに堀江貴文氏と対談。ホリエモンAI学校建築校のローンチを発表。","attendees":"","satisfaction":"","event_url":"https://www.youtube.com/watch?v=poAUbKmJn9A","video_url":"","report_url":""},
    {"date":"2025/06/28","event":"三崎優太 元青汁王子のyoutubeチャンネルに出演","venue":"YOUTUBE","session":"PGHOUSE浜松を三崎優太氏が紹介。代表取締役の白都卓磨が出演","theme":"賃貸より安く理想のマイホームに住む方法を見つけてしまいました。","attendees":"","satisfaction":"","event_url":"https://www.youtube.com/watch?v=T2nW0Un2SDY","video_url":"","report_url":""},
    {"date":"2024/12/15","event":"LIFULL HOME主催オンラインセミナー","venue":"オンライン","session":"LIFEFULL HOME主催オンラインセミナーにCXデザインの石野祐太朗が登壇","theme":"成果の裏側も包み隠さず公開！静岡県の地場工務店が1年間で紹介来場者数を5倍にアップした取り組みとは？","attendees":"","satisfaction":"","event_url":"https://iezukuri-business.homes.jp/seminars/seminars-00106","video_url":"","report_url":""},
    {"date":"2023/09/08","event":"ダイテック主催「攻めと守りの工務店経営」セミナー","venue":"オンライン","session":"ダイテック主催セミナーに代表取締役の白都卓磨とCXデザインの石野祐太朗が登壇","theme":"静岡県内で5年で5倍の企業成長を実現！株式会社LIFEFUNDの戦略・取り組み公開","attendees":"","satisfaction":"","event_url":"https://www.kensetsu-cloud.jp/seminar/daitec-live28/","video_url":"","report_url":""},
    {"date":"2023/11/14","event":"リブコンサルティング主催「家づくりガイド活用術」セミナー","venue":"オンライン","session":"リブコンサルティング主催セミナーにCXデザインの石野祐太朗が登壇","theme":"建築中のオーナー様の満足度もアップ！オーナーズサイトで届ける『家づくりガイド』活用術","attendees":"","satisfaction":"","event_url":"","video_url":"","report_url":""},
  ],

  awards: [
    {"date":"2026/06/08","title":"イエタテ 2026年上半期 静岡県西部エリア人気ランキング ― ARRCH 4位","detail":"ARRCHブランド","url":"https://www.arrch.net/article/p11304/","crown":""},
    {"date":"2026/06/08","title":"イエタテ 2026年上半期 静岡県西部エリア人気ランキング ― PGHOUSE 8位","detail":"PGHOUSEブランド","url":"https://hamamatsu.pg-house.jp/news/notice-ietate-ranking/","crown":""},
    {"date":"2026/01/06","title":"イエタテ 2025年下半期 静岡県西部エリア人気ランキング — ARRCH 4位","detail":"ARRCHブランド","url":"https://www.arrch.net/article/p8295/","crown":""},
    {"date":"2026/01/06","title":"イエタテ 2025年下半期 静岡県西部エリア人気ランキング — PGHOUSE 6位","detail":"PGHOUSEブランド（オープン1年未満での受賞）","url":"https://hamamatsu.pg-house.jp/news/26010601/","crown":""},
    {"date":"2025/10/03","title":"イエタテ 浜松市工務店ランキング — PGHOUSE 第3位","detail":"PGHOUSEブランド(開業数ヶ月での受賞)","url":"https://hamamatsu.pg-house.jp/news/251003/","crown":""},
    {"date":"2025/01/21","title":"「Ambassador Cloud Award 2025」 アンバサダー経営優秀賞 受賞","detail":"顧客に愛される住宅会社としての実績が評価される。","url":"https://www.ambassador-cloud.biz/news/news250121/","crown":""},
    {"date":"2024/12/31","title":"「Ambassador Cloud Award 2024」 特別賞 受賞","detail":"顧客に愛される住宅会社としての実績が評価される","url":"","crown":""},
    {"date":"2024/08/29","title":"イエタテ 2024年上半期 静岡県西部エリア人気ランキング — ARRCH 4位","detail":"ARRCHブランド","url":"https://www.arrch.net/article/p1800/","crown":""},
    {"date":"2023/12/31","title":"「Ambassador Cloud Award 2023」アンバサダー経営優秀賞 受賞","detail":"顧客に愛される住宅会社としての実績が評価される","url":"","crown":""},
    {"date":"2023/12/31","title":"デザインカーサ「建築家とつくる家」設計数 5年連続日本一","detail":"2019年から5年連続受賞により殿堂入り。ARRCHブランド","url":"","crown":""},
    {"date":"2022/12/31","title":"デザインカーサ「建築家とつくる家」設計数 4年連続日本一","detail":"ARRCHブランド","url":"","crown":""},
    {"date":"2021/12/31","title":"デザインカーサ「建築家とつくる家」設計数 3年連続日本一","detail":"ARRCHブランド","url":"","crown":""},
    {"date":"2020/12/31","title":"デザインカーサ「建築家とつくる家」設計数 2年連続日本一","detail":"ARRCHブランド","url":"","crown":""},
    {"date":"2019/12/31","title":"デザインカーサ「建築家とつくる家」設計数 日本一（初受賞）","detail":"ARRCHブランド。5年連続受賞・殿堂入りへの第一歩","url":"","crown":""},
  ],

  vision: [
    {"target_year":"2036","name":"BLUEPRINT 2036（10年ビジョン）","detail":"2026年1月発表。2036年までに売上150億円・年間436棟・社員一人当たり売上1億円を目標に。静岡県中部への出店も視野。","url":"https://prtimes.jp/main/html/rd/p/000000014.000160136.html","url_label":""},
  ],

  topics: [
    {"topic":"建築業界「AI活用100本ノック」公開","detail":"現場で試してきた100のAI活用事例","url":"https://kenchikuaikeiei.github.io/ai-prompts/100knock.pdf","url_label":""},
    {"topic":"ホリエモンAI学校「建築校」開校","detail":"建築業界特化の生成AI教育事業。全国工務店向けに展開中","url":"https://kenchiku-ai.com/","url_label":""},
    {"topic":"建築AI経営研究会を立ち上げ","detail":"「AIで建築業界を高生産産業へリメイクする」実装型コミュニティ","url":"https://kenchiku-ai.com/","url_label":""},
    {"topic":"年間100棟・売上13倍達成","detail":"2015年新築事業立ち上げからわずか10年で年間100棟・売上高27.1億円（13倍）の地域トップビルダーに成長。年平均成長率33.1%。","url":"https://prtimes.jp/main/html/rd/p/000000014.000160136.html","url_label":""},
    {"topic":"PGパーク浜松オープン","detail":"静岡県下最大規模の体感型住宅展示場「PGパーク浜松」を開設（曳馬）。","url":"https://prtimes.jp/main/html/rd/p/000000001.000160136.html","url_label":""},
    {"topic":"年間休日120日導入","detail":"2025年11月より正社員全員の年間休日を110日→120日へ引き上げ（建設業界平均108日を大きく上回る水準）。給与水準は維持。","url":"https://prtimes.jp/main/html/rd/p/000000016.000160136.html","url_label":""},
    {"topic":"つながる相続（相続コンサル）","detail":"建築・不動産・相続のワンストップ体制を確立。","url":"","url_label":""},
    {"topic":"湖のマルシェ（地域貢献）","detail":"浜松城公園で開催した地域密着イベント。7年間で来場2.9万人。2025年は過去最多70店舗が出店。","url":"https://mizuuminomarche.com/","url_label":""},
  ],

  variables: [
    {"key":"年間棟数","value":"年間100棟","updated_at":"2026-09-27"},
    {"key":"注文住宅棟数_最新","value":"114棟","updated_at":"2026-09-27"},
    {"key":"売上年度","value":"2025年","updated_at":"2026-09-27"},
    {"key":"売上高_最新","value":"27.1億円","updated_at":"2026-09-27"},
    {"key":"売上成長倍率","value":"13倍","updated_at":"2026-09-27"},
    {"key":"過去10年平均成長率","value":"33.1%","updated_at":"2026-09-27"},
    {"key":"従業員数","value":"73名","updated_at":"2026-09-27"},
    {"key":"資本金","value":"500万円","updated_at":"2026-09-27"},
    {"key":"今期申込契約数","value":"148棟","updated_at":"2026-09-27"},
  ],

  company: [
    {"label":"社名","value":"株式会社LIFEFUND","note":"","highlight":""},
    {"label":"代表者","value":"代表取締役 白都 卓磨","note":"","highlight":"TRUE"},
    {"label":"設立","value":"1972年","note":"前身法人の設立年","highlight":"TRUE"},
    {"label":"沿革","value":"2011年 白都卓磨が独立し、代表取締役に就任\n2015年 新築事業を本格化\n2023年 社名を株式会社LIFEFUNDに変更","note":"","highlight":""},
    {"label":"本社所在地","value":"静岡県浜松市中央区鴨江3丁目70番23号","note":"","highlight":""},
    {"label":"資本金","value":"{{資本金}}","note":"","highlight":""},
    {"label":"従業員数","value":"{{従業員数}}","note":"","highlight":"TRUE"},
    {"label":"売上高","value":"{{売上高_最新}}","note":"{{売上年度}}実績／10年で{{売上成長倍率}}","highlight":"TRUE"},
    {"label":"年間棟数","value":"{{注文住宅棟数_最新}}","note":"{{売上年度}}実績・注文住宅","highlight":""},
    {"label":"今期の申込・契約数","value":"{{今期申込契約数}}","note":"2026年7月〜2027年6月期のARRCHパートナー申込数とPGHOUSE請負契約数の合計（実績ではありません）","highlight":""},
    {"label":"事業内容","value":"注文住宅の設計・施工（ARRCH／PGHOUSE）\n不動産事業（物件王国）\n相続コンサルティング（つながる相続）\n建築業界向けAIスクール・研究会の運営","note":"","highlight":""},
    {"label":"主なブランド","value":"ARRCH／PGHOUSE／物件王国／つながる相続","note":"","highlight":"TRUE"},
  ],

  contact: [
    {"label":"担当","value":"石野 祐太朗（PR担当）","type":"text","link_label":""},
    {"label":"メール","value":"pr.lifefund@gmail.com","type":"email","link_label":""},
    {"label":"電話","value":"053-488-8910","type":"tel","link_label":""},
    {"label":"プレスリリース","value":"https://prtimes.jp/main/html/searchrlp/company_id/160136","type":"url","link_label":"PR TIMES 配信一覧"},
  ],

  ceoProfiles: [
    {"no":"0","scene":"正本","text":"株式会社LIFEFUND 代表取締役。白都 卓磨（はくと たくま）。1988年、静岡県浜松市生まれ。建築・不動産領域での実務経験を起点に、2011年に独立。2015年に新築事業を本格化し、地方都市・浜松発の住宅会社でありながら、10年で{{年間棟数}}を超えるトップビルダーへと成長させた。\n\n現在は、注文住宅ブランド「ARRCH」、高性能住宅ブランド「PGHOUSE」、不動産事業「物件王国」、相続コンサルティング「つながる相続」などを展開。住宅・不動産・相続を横断し、住まいを入口に、家族・資産・地域の未来を支える生活インフラ企業への進化を進めている。\n\n注文住宅領域では、建築家住宅の分野に早くから取り組み、全国規模の建築家住宅ネットワークにおいて5年連続日本一を達成し、殿堂入り。デザイン性と事業成長を両立する、地方都市発のビルダー成長モデルを実践している。\n\nAI領域では、住宅・建築業界における先進的な実装企業として、設計・施工・営業・採用・マーケティングなど自社業務の各領域にAI活用を導入。その実践知をもとに、現役の建築会社が運営する業界特化型AIスクール「ホリエモンAI学校 建築校」や、全国の建築会社が参加する「建築AI経営研究会」を展開している。現場で使えるAI活用を、業界全体の生産性向上につながる実装知として共有している。\n\n{{売上年度}}には売上高{{売上高_最新}}を達成。新築事業本格化以降、過去10年平均成長率{{過去10年平均成長率}}で成長を続けている。住宅会社の枠を超え、建築・不動産・相続・AIを横断する次世代の生活インフラ企業として、地方都市から住宅業界の新しい経営モデルづくりに挑戦している。","featured_on_mediakit":"TRUE","source_label":"プロフィール正本（全用途の原本・汎用の詳細版）","source_url":"","keywords":"正本 マスター 公式 ARRCH PGHOUSE 物件王国 つながる相続 AI 建築AI経営研究会 ホリエモンAI学校 日本一 殿堂入り"},
    {"no":"2","scene":"メディア","text":"1988年静岡県浜松市生まれ。建築・不動産業界での経験を経て、2015年に新築事業を立ち上げ、株式会社LIFEFUNDを設立。わずか10年で年間100棟を手がける地域トップビルダーへと成長させた。建築家住宅「ARRCH」や高性能住宅「PGHOUSE」を展開し、設計・施工・営業・採用・マーケティングなど全領域にAIを導入。アナログな住宅業界の非効率を構造から変革中。「あらゆる人が喜びある人生を叶えられる地域社会をつくる」というビジョンのもと、事業を“家づくり”にとどまらず“人づくり・まちづくり”へと発展させている。AIを人の可能性を広げる力として活用し、人が喜びをもって生きられる社会の実現を目指し、地域から業界の未来をデザインしている。","featured_on_mediakit":"","source_label":"新建ハウジング","source_url":"https://www.s-housing.jp/archives/416428","keywords":"新建ハウジング AI 全領域 アナログ 業界 構造 変革 ビジョン 人づくり まちづくり 業界の未来"},
    {"no":"4","scene":"メディア","text":"白都 卓磨 (Hakuto Takuma)\n株式会社LIFEFUND 代表取締役\n1988年静岡県浜松市生まれ。建築・不動産業界での経験を経て、2015年に株式会社LIFEFUNDを設立。わずか10年で年間100棟を手がける地域トップビルダーへと成長させる。\n建築家住宅「ARRCH」や高性能住宅「PGHOUSE」に加え、不動産仲介・買取再販事業「物件王国」、相続コンサルティング事業「つながる相続」など多角的に展開。\n建築・不動産・相続を横断する総合ブランドを築き上げ、アナログな業界構造の変革に挑む実業家。設計から施工、マーケティングに至る全領域にAIを実装し、次世代の経営モデルを確立している。","featured_on_mediakit":"","source_label":"建築AI","source_url":"https://kenchiku-ai.com/2603-2/","keywords":"建築AI 多角的 物件王国 つながる相続 総合ブランド 実業家 経営モデル 次世代"},
    {"no":"7","scene":"セミナー","text":"**登壇者紹介**\n白都 卓磨 氏\n株式会社LIFEFUND 代表取締役\n\n《建築家と建てる家ARRCH》\nhttps://www.arrch.net/\n《性能コスパ住宅PGHOUSE》\nhttps://hamamatsu.pg-house.jp/\n《ホリエモンAI学校建築校》\nhttps://kenchiku-ai.com/\n\n1988年静岡県浜松市生まれ。建築・不動産業界での経験を経て、2015年に新築事業を立ち上げ、株式会社LIFEFUNDを設立。わずか10年で年間100棟を手がける地域トップビルダーへと成長させた。建築家住宅「ARRCH」や高性能住宅「PGHOUSE」を展開し、設計・施工・営業・採用・マーケティングなど全領域にAIを導入。アナログな住宅業界の非効率を構造から変革中。 「あらゆる人が喜びある人生を叶えられる地域社会をつくる」というビジョンのもと、事業を“家づくり”にとどまらず“人づくり・まちづくり”へと発展させている。AIを人の可能性を広げる力として活用し、人が喜びをもって生きられる社会の実現を目指し、地域から業界の未来をデザインしている。","featured_on_mediakit":"","source_label":"PR TIMES（ホリエモンAI学校建築校）","source_url":"https://prtimes.jp/main/html/rd/p/000000013.000160136.html","keywords":"PR TIMES ホリエモンAI学校 建築校 登壇者 ARRCH PGHOUSE URL付き ビジョン 人づくり まちづくり"},
    {"no":"8","scene":"セミナー","text":"株式会社LIFEFUND 代表取締役\n白都 卓磨\n\n1988年静岡県浜松市生まれ。建築・不動産業界での経験を経て、2015年に新築事業を立ち上げ、株式会社LIFEFUNDを設立。10年で年間100棟の地域トップビルダーへと成長させる。建築住宅「ARRCH」や高性能住宅「PGHOUSE」を展開し設計・施工・営業・採用・マーケティングなど全領域にAIを導入。相続コンサルティング事業「つながる相続」を立ち上げ、建築・不動産・相続を横断する地域総合ブランドとして発展を続けている。","featured_on_mediakit":"","source_label":"JGBA セミナー","source_url":"https://jgba.net/event/2026-2-10-jgba-seminar/","keywords":"JGBA 登壇者 つながる相続 地域総合ブランド 簡潔"},
    {"no":"101","scene":"汎用","text":"株式会社LIFEFUND 代表取締役。1988年静岡県浜松市生まれ。2011年に独立し、2015年に新築事業を本格化。10年で{{年間棟数}}を超えるトップビルダーへと成長させた。注文住宅「ARRCH」、高性能住宅「PGHOUSE」、不動産事業「物件王国」、相続コンサルティング「つながる相続」を展開し、住まいを入口にした生活インフラ企業づくりに挑む。","featured_on_mediakit":"","source_label":"正本から展開：汎用・短文","source_url":"","keywords":"汎用 短文 正本"},
    {"no":"102","scene":"汎用","text":"株式会社LIFEFUND 代表取締役。白都 卓磨（はくと たくま）。1988年静岡県浜松市生まれ。建築・不動産領域での実務経験を起点に2011年に独立し、2015年に新築事業を本格化。地方都市・浜松発の住宅会社として、10年で{{年間棟数}}を超えるトップビルダーへと成長させた。注文住宅「ARRCH」、高性能住宅「PGHOUSE」、不動産事業「物件王国」、相続コンサルティング「つながる相続」を展開。自社業務へのAI実装の実践知を、「ホリエモンAI学校 建築校」や「建築AI経営研究会」で業界に共有している。","featured_on_mediakit":"","source_label":"正本から展開：汎用・標準","source_url":"","keywords":"汎用 標準 正本"},
    {"no":"201","scene":"講演","text":"株式会社LIFEFUND 代表取締役。浜松を拠点に、10年で{{年間棟数}}を超えるトップビルダーへと会社を成長させた住宅会社経営者。住宅・不動産・相続を横断する事業づくりと、自社業務へのAI実装の実践をもとに、全国の工務店経営者や住まいを考える方に向けて講演している。","featured_on_mediakit":"","source_label":"正本から展開：講演・短文","source_url":"","keywords":"講演 短文 正本"},
    {"no":"202","scene":"講演","text":"株式会社LIFEFUND 代表取締役。1988年静岡県浜松市生まれ。2011年に独立し、2015年に新築事業を本格化。地方都市・浜松発の住宅会社として10年で{{年間棟数}}を超えるトップビルダーへと成長させ、{{売上年度}}には売上高{{売上高_最新}}を達成した。注文住宅「ARRCH」、高性能住宅「PGHOUSE」、不動産事業「物件王国」、相続コンサルティング「つながる相続」を展開。経営とAI活用の実践を、Japan Home Show「工務店経営会議2025」など全国のセミナーで発信している。","featured_on_mediakit":"","source_label":"正本から展開：講演・標準","source_url":"","keywords":"講演 標準 正本"},
    {"no":"203","scene":"講演","text":"株式会社LIFEFUND 代表取締役。白都 卓磨（はくと たくま）。1988年静岡県浜松市生まれ。建築・不動産領域での実務経験を起点に2011年に独立し、2015年に新築事業を本格化。地方都市・浜松発の住宅会社でありながら、10年で{{年間棟数}}を超えるトップビルダーへと成長させた。{{売上年度}}の売上高は{{売上高_最新}}、新築事業本格化以降の過去10年平均成長率は{{過去10年平均成長率}}。\n\n現在は注文住宅ブランド「ARRCH」、高性能住宅ブランド「PGHOUSE」、不動産事業「物件王国」、相続コンサルティング「つながる相続」を展開し、住まいを入口に家族・資産・地域の未来を支える生活インフラ企業への進化を進めている。\n\n設計・施工・営業・採用・マーケティングの各領域にAIを導入した実践をもとに、業界特化型AIスクール「ホリエモンAI学校 建築校」と、全国の建築会社が参加する「建築AI経営研究会」を展開。Japan Home Show「工務店経営会議2025」など全国のセミナーに登壇し、地方の住宅会社が成長を続けるための経営とAI活用を語っている。","featured_on_mediakit":"","source_label":"正本から展開：講演・詳細","source_url":"","keywords":"講演 詳細 正本"},
    {"no":"301","scene":"メディア","text":"白都 卓磨（はくと・たくま）　株式会社LIFEFUND代表取締役。1988年静岡県浜松市生まれ。2011年に独立し、2015年に新築事業を本格化。10年で{{年間棟数}}を超えるトップビルダーに成長させた。注文住宅「ARRCH」「PGHOUSE」、不動産事業「物件王国」、相続コンサルティング「つながる相続」を展開する。","featured_on_mediakit":"","source_label":"正本から展開：メディア・短文","source_url":"","keywords":"メディア 短文 正本"},
    {"no":"302","scene":"メディア","text":"白都 卓磨（はくと・たくま）　株式会社LIFEFUND代表取締役。1988年静岡県浜松市生まれ。2011年に独立し、2015年に新築事業を本格化。10年で{{年間棟数}}を超えるトップビルダーへと成長させ、{{売上年度}}の売上高は{{売上高_最新}}。注文住宅「ARRCH」は全国規模の建築家住宅ネットワークで5年連続日本一を達成し殿堂入り。高性能住宅「PGHOUSE」、不動産事業「物件王国」、相続コンサルティング「つながる相続」も展開し、業界特化型AIスクール「ホリエモンAI学校 建築校」を運営する。","featured_on_mediakit":"","source_label":"正本から展開：メディア・標準","source_url":"","keywords":"メディア 標準 正本"},
    {"no":"303","scene":"メディア","text":"白都 卓磨（はくと・たくま）　株式会社LIFEFUND代表取締役。1988年静岡県浜松市生まれ。建築・不動産領域での実務経験を起点に2011年に独立し、2015年に新築事業を本格化。地方都市・浜松発の住宅会社として、10年で{{年間棟数}}を超えるトップビルダーへと成長させた。{{売上年度}}の売上高は{{売上高_最新}}で、新築事業本格化以降の過去10年平均成長率は{{過去10年平均成長率}}。\n\n注文住宅ブランド「ARRCH」では建築家住宅に早くから取り組み、全国規模の建築家住宅ネットワークにおいて5年連続日本一を達成し殿堂入り。ほかに高性能住宅ブランド「PGHOUSE」、不動産事業「物件王国」、相続コンサルティング「つながる相続」を展開し、住宅・不動産・相続を横断する生活インフラ企業への進化を進めている。\n\nAI領域では、設計・施工・営業・採用・マーケティングなど自社業務の各領域にAIを導入。その実践知をもとに、現役の建築会社が運営する業界特化型AIスクール「ホリエモンAI学校 建築校」（2025年7月開校）と、全国の建築会社が参加する「建築AI経営研究会」（2025年11月発足）を展開している。","featured_on_mediakit":"","source_label":"正本から展開：メディア・詳細","source_url":"","keywords":"メディア 詳細 正本"},
    {"no":"401","scene":"AI講演","text":"株式会社LIFEFUND 代表取締役。浜松の住宅会社を10年で{{年間棟数}}を超えるトップビルダーへと成長させる中で、設計・施工・営業・採用・マーケティングの各業務にAIを導入。その実践知をもとに、業界特化型AIスクール「ホリエモンAI学校 建築校」と「建築AI経営研究会」を展開している。","featured_on_mediakit":"","source_label":"正本から展開：AI講演・短文","source_url":"","keywords":"AI講演 短文 正本"},
    {"no":"402","scene":"AI講演","text":"株式会社LIFEFUND 代表取締役。1988年静岡県浜松市生まれ。2015年に新築事業を本格化し、10年で{{年間棟数}}を超えるトップビルダーへと成長させた。住宅・建築業界におけるAIの先進的な実装企業として、自社業務の各領域にAIを導入。「AIを使ったら給料が上がる」制度では、3か月で社員から177件の活用事例が集まった。その実践知をもとに、現役の建築会社が運営する「ホリエモンAI学校 建築校」と、全国の建築会社が参加する「建築AI経営研究会」を展開している。","featured_on_mediakit":"","source_label":"正本から展開：AI講演・標準","source_url":"","keywords":"AI講演 標準 正本"},
    {"no":"403","scene":"AI講演","text":"株式会社LIFEFUND 代表取締役。白都 卓磨（はくと たくま）。1988年静岡県浜松市生まれ。2011年に独立し、2015年に新築事業を本格化。地方都市・浜松発の住宅会社として、10年で{{年間棟数}}を超えるトップビルダーへと成長させた。\n\n住宅・建築業界におけるAIの先進的な実装企業として、設計・施工・営業・採用・マーケティングなど自社業務の各領域にAI活用を導入。「AIを使ったら給料が上がる」制度を設けたところ、3か月で社員から177件の活用事例が集まった。\n\nその実践知をもとに、現役の建築会社が運営する業界特化型AIスクール「ホリエモンAI学校 建築校」（2025年7月開校）と、全国の建築会社が参加する「建築AI経営研究会」（2025年11月発足）を展開。現場で使えるAI活用を、業界全体の生産性向上につながる実装知として共有している。AIを経営と現場の両方にどう根づかせるかを、住宅会社の経営者の立場から語る。","featured_on_mediakit":"","source_label":"正本から展開：AI講演・詳細","source_url":"","keywords":"AI講演 詳細 正本"},
    {"no":"501","scene":"相続講演","text":"株式会社LIFEFUND 代表取締役。浜松を拠点に、注文住宅・不動産・相続を横断して手がける。相続コンサルティング「つながる相続」を展開し、住まいと不動産の実務を知る立場から、家族の住まいと資産の引き継ぎを支援している。","featured_on_mediakit":"","source_label":"正本から展開：相続講演・短文","source_url":"","keywords":"相続講演 短文 正本"},
    {"no":"502","scene":"相続講演","text":"株式会社LIFEFUND 代表取締役。1988年静岡県浜松市生まれ。建築・不動産領域での実務経験を起点に2011年に独立し、10年で{{年間棟数}}を超えるトップビルダーへと会社を成長させた。注文住宅「ARRCH」「PGHOUSE」に加え、不動産事業「物件王国」、相続コンサルティング「つながる相続」を展開。家づくりから不動産の活用・売却、相続までを一つの窓口で相談できる体制をつくり、相続セミナーは2か月連続で満席となった。","featured_on_mediakit":"","source_label":"正本から展開：相続講演・標準","source_url":"","keywords":"相続講演 標準 正本"},
    {"no":"503","scene":"相続講演","text":"株式会社LIFEFUND 代表取締役。白都 卓磨（はくと たくま）。1988年静岡県浜松市生まれ。建築・不動産領域での実務経験を起点に2011年に独立。2015年に新築事業を本格化し、地方都市・浜松発の住宅会社として10年で{{年間棟数}}を超えるトップビルダーへと成長させた。\n\n現在は注文住宅ブランド「ARRCH」、高性能住宅ブランド「PGHOUSE」、不動産事業「物件王国」、相続コンサルティング「つながる相続」を展開。家を建てる、不動産を活かす・売る、次の世代へ引き継ぐまでを一社で相談できる体制をつくっている。相続セミナーは2か月連続で満席となり、参加者の約6割がその場で個別相談を希望した。\n\n住まいを入口に、家族・資産・地域の未来を支える生活インフラ企業を目指す経営者として、住まいと資産をどう守り、どう引き継ぐかを、建築・不動産の現場の事例とともに伝えている。","featured_on_mediakit":"","source_label":"正本から展開：相続講演・詳細","source_url":"","keywords":"相続講演 詳細 正本"},
    {"no":"601","scene":"注文住宅ビルダー向け講演","text":"株式会社LIFEFUND 代表取締役。2015年に新築事業を本格化し、地方都市・浜松で10年で{{年間棟数}}を超えるトップビルダーへと成長させた。注文住宅「ARRCH」は全国規模の建築家住宅ネットワークで5年連続日本一を達成し殿堂入り。デザインと事業成長を両立するビルダー経営を実践している。","featured_on_mediakit":"","source_label":"正本から展開：注文住宅ビルダー向け講演・短文","source_url":"","keywords":"注文住宅ビルダー向け講演 短文 正本"},
    {"no":"602","scene":"注文住宅ビルダー向け講演","text":"株式会社LIFEFUND 代表取締役。1988年静岡県浜松市生まれ。2015年に新築事業を本格化し、地方都市・浜松発の住宅会社として10年で{{年間棟数}}を超えるトップビルダーへと成長させた。{{売上年度}}の売上高は{{売上高_最新}}。建築家住宅に早くから取り組んだ注文住宅「ARRCH」は、全国規模の建築家住宅ネットワークで5年連続日本一を達成し殿堂入り。高性能住宅「PGHOUSE」とあわせ、デザイン性と事業成長を両立する地方ビルダーの成長モデルを実践している。","featured_on_mediakit":"","source_label":"正本から展開：注文住宅ビルダー向け講演・標準","source_url":"","keywords":"注文住宅ビルダー向け講演 標準 正本"},
    {"no":"603","scene":"注文住宅ビルダー向け講演","text":"株式会社LIFEFUND 代表取締役。白都 卓磨（はくと たくま）。1988年静岡県浜松市生まれ。建築・不動産領域での実務経験を起点に2011年に独立し、2015年に新築事業を本格化。住宅着工が減り続ける中、地方都市・浜松発の住宅会社を10年で{{年間棟数}}を超えるトップビルダーへと成長させた。{{売上年度}}の売上高は{{売上高_最新}}、新築事業本格化以降の過去10年平均成長率は{{過去10年平均成長率}}。\n\n注文住宅ブランド「ARRCH」では建築家住宅の分野に早くから取り組み、全国規模の建築家住宅ネットワークにおいて5年連続日本一を達成し殿堂入り。高性能住宅ブランド「PGHOUSE」では、体感型住宅展示場「PGパーク浜松」を開設した。\n\n設計・施工・営業・採用・マーケティングの各領域へのAI導入や、年間休日120日への引き上げなど、生産性と働き方の両面から住宅会社の経営を変えてきた実践を、全国の工務店・ビルダー経営者に向けて伝えている。","featured_on_mediakit":"","source_label":"正本から展開：注文住宅ビルダー向け講演・詳細","source_url":"","keywords":"注文住宅ビルダー向け講演 詳細 正本"},
  ],

  ceoLinks: [
    {"title":"社長名鑑","description":"創業の経緯、事業内容、今後のビジョンまで網羅したロングインタビュー記事です。","url":"https://shachomeikan.jp/industry_article/4855"},
    {"title":"Japan Quality / Japan Pride","description":"仕事への想いや原点となるエピソードが掲載されています。","url":"https://japanpride.jp/person/hakuto_takuma/"},
    {"title":"Wantedly（LIFEFUND公式）","description":"「『家』を通じて『人生』をつくる」と題した、本人の原点と未来を語る記事です。","url":"https://www.wantedly.com/companies/company_5410460/post_articles/988749"},
  ],

  brands: [
    {"name":"ARRCH","category":"注文住宅","description":"建築家とつくる注文住宅ブランド。デザインカーサ「建築家とつくる家」設計数で2019年から5年連続日本一を獲得し、殿堂入り。","url":"https://www.arrch.net/","url_label":"arrch.net"},
    {"name":"PGHOUSE","category":"高性能住宅","description":"超耐震×自由設計の高性能住宅ブランド。2025年5月に体感型住宅展示場「PGパーク浜松」を開設。","url":"https://hamamatsu.pg-house.jp/","url_label":"hamamatsu.pg-house.jp"},
    {"name":"物件王国","category":"不動産事業","description":"不動産仲介・買取再販・収益不動産・民泊などを手がける不動産事業。","url":"https://www.bukkenking.com/","url_label":"bukkenking.com"},
    {"name":"つながる相続","category":"相続コンサルティング","description":"住まい・不動産とあわせて相続を相談できる相続コンサルティング。2025年開始、相続セミナーは2カ月連続で満席。","url":"","url_label":""},
    {"name":"ホリエモンAI学校 建築校","category":"AIスクール","description":"現役の建築会社が運営する、建築業界特化型のAIスクール。2025年7月開校。","url":"https://kenchiku-ai.com/","url_label":"kenchiku-ai.com"},
    {"name":"建築AI経営研究会","category":"経営者コミュニティ","description":"全国の建築会社経営者が参加する、AI実装のための研究会。2025年11月発足。","url":"","url_label":""},
  ],

  themes: [
    {"theme":"地方工務店のAI経営","detail":"設計・施工・営業・採用・マーケティングまで、自社業務の全領域にAIを導入。「AIを使ったら給料が上がる」制度で、3ヶ月で社員から177件の活用事例が集まった。","url":"https://prtimes.jp/main/html/rd/p/000000044.000160136.html","url_label":"関連リリース"},
    {"theme":"縮小市場で伸びる住宅会社の経営","detail":"住宅着工が減り続ける中、2015年の新築事業本格化から10年で売上{{売上成長倍率}}・{{年間棟数}}に。地方都市発のビルダー成長モデル。","url":"https://prtimes.jp/main/html/rd/p/000000014.000160136.html","url_label":"関連リリース"},
    {"theme":"建築家住宅とデザイン経営","detail":"ARRCHがデザインカーサ「建築家とつくる家」設計数で5年連続日本一・殿堂入り。デザイン性と事業成長の両立。","url":"https://www.arrch.net/about/history/","url_label":"受賞歴"},
    {"theme":"住宅会社が担う相続","detail":"相続セミナーが2カ月連続で満席、約6割がその場で個別面談を希望。住まい・不動産・相続を一体で相談できる体制づくり。","url":"https://prtimes.jp/main/html/rd/p/000000050.000160136.html","url_label":"関連リリース"},
    {"theme":"建設業の働き方改革","detail":"2025年11月から正社員の年間休日を110日から120日へ引き上げ（給与水準は維持）。","url":"https://prtimes.jp/main/html/rd/p/000000016.000160136.html","url_label":"関連リリース"},
    {"theme":"建築業界のAI人材育成","detail":"「ホリエモンAI学校 建築校」と「建築AI経営研究会」を通じて、現場で使えるAI活用を業界全体に共有。","url":"https://prtimes.jp/main/html/rd/p/000000011.000160136.html","url_label":"関連リリース"},
    {"theme":"地域とつながる住宅会社","detail":"赤字1,000万円でも続けてきた「湖のマルシェ」は、7年で来場2.9万人に。","url":"","url_label":""},
    {"theme":"住宅市場の足元の変化","detail":"建材供給（ナフサ危機・断熱材）、住宅ローン金利の上昇、人手不足など、現場から見た住宅市場の動き。","url":"https://prtimes.jp/main/html/rd/p/000000051.000160136.html","url_label":"関連リリース"},
  ],

  assets: [
  ],

  usage: [
    {"note":"本素材は、株式会社LIFEFUNDおよび当社ブランド・代表に関する報道・記事・番組・イベント告知の目的に限りご利用いただけます。"},
    {"note":"ロゴは縦横比の変更、色の変更、変形、他の要素との合成などの加工をせずにご使用ください。"},
    {"note":"代表写真はトリミングのみ可とし、合成・色調補正・反転などの加工はご遠慮ください。"},
    {"note":"クレジットが必要な場合は「写真提供：株式会社LIFEFUND」とご表記ください。"},
    {"note":"売上高・棟数などの数値は更新されます。掲載時は本ページ「会社概要」の最新値をご参照ください。"},
    {"note":"広告・販促物など報道以外の目的でのご利用、第三者への再配布は、事前にご相談ください。"},
    {"note":"掲載・放送の前に、事実確認のためご一報いただけますと幸いです。掲載後は媒体名・URLをお知らせください。"},
  ],
};
